name: Deploy Spring Boot App

on:
  push:
    branches:
      - master  # Замени на нужную ветку при необходимости

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY_BACKEND }}

      - name: Sync project to EC2
        run: |
          rsync -avz --exclude='.git' --exclude='target/' --exclude='.github' -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.EC2_SSH_USER_BACKEND }}@${{ secrets.EC2_HOST_BACKEND }}:/home/${{ secrets.EC2_SSH_USER_BACKEND }}/chime-chat-back

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_SSH_USER_BACKEND }}@${{ secrets.EC2_HOST_BACKEND }} << 'EOF'
            cd chime-chat-back
            docker compose down
            docker compose up -d --build
          EOF
